### ISSUE TITLE
Spotify crashes when I try to log in.

### ISSUE THREAD

**Issue by rpalmcos** [gabrieldenoni/SpotifyClone#1]
Hi, I am kinda new to Swift and coding in general. I have followed the instructions in the read me file and have setup an app within Spotify developer and added a new user. I am stuck on how to log into Spotify within the SpotifyClone. Most likely a simple fix but I appreciate any help! Thank you :)

**Comment by gabrieldenoni** [comment]
Hi! What problem are you having when you try to log-in ?

**Comment by rpalmcos** [comment]
HI, thanks for your reply! I managed to fix it by copying and pasting the link in the authentication code into the redirect link in the edit settings, of the Spotify dashboard!
